apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
  labels:
    app: flask-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
      - name: flask-hello-world
        image: tiangolo/uwsgi-nginx-flask:python3.8
        ports:
        - containerPort: 80
        env:
        - name: MODULE_NAME
          value: main
        - name: FLASK_APP
          value: main.py
        volumeMounts:
        - name: app-code
          mountPath: /app
      volumes:
      - name: app-code
        configMap:
          name: flask-hello-world-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-hello-world-app
  labels:
    app: flask-hello-world
data:
  main.py: |
    from flask import Flask
    app = Flask(__name__)
    @app.route('/')
    def hello():
        return "Hello, Flask on Kubernetes!"
